### ISSUE TITLE
hiding tabs bar and keeping the left side bookmark

### ISSUE THREAD

**Issue by MAFiA303** [Godiesc/opera-gx#20]
first of all great work.

I usually hide my tabs bar because i use tree tabs
```css
#TabsToolbar {
   visibility: collapse;
 }
```

this also hides left side bookmarks  `ogx_left-sidebar.css`
how can i hide tabs and keep bookmarks on the left side?

**Comment by Godiesc** [comment]
I don't use the tree tabs style, so difficult to me see what is wrong, I use the code you share and the tabs disappear but keep the left side bar, are you using css to tree tabs style or an extension?

**Comment by MAFiA303** [comment]
it is almost working.

I added this code the end of the userChrome.css
```css
/* to hide the native tabs */
#TabsToolbar {
  visibility: collapse;
}

#titlebar {
visibility: collapse;
}

/* leaves space for the window buttons */
#nav-bar {
  margin-top: 2px;
}

/* change maximum/minimum width restriction of sidebar */
#sidebar {
max-width: none !important;
min-width: 30px !important;
}

#sidebar-header {
  display: none;
}
```
now the firefox menu is gone. i need to move it lower somehow

![image](https://user-images.githubusercontent.com/3491396/194711375-68fe8059-f1e9-4308-81a0-fbb2d446685e.png)
